version: '3'

services:
  venus-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=venus
      - MYSQL_USER=venus
      - MYSQL_PASSWORD=venus
    ports:
      - 3306:3306
  backend-api: 
    restart: on-failure:5
    build:
      context: ./vega-spring-master
      dockerfile: ./Dockerfile
    image: "venus/beeple"
    volumes:
      - ./vega-spring-master:/workspace/app
    ports:
      - "8080:8080"
  backend-web:
    build:
      context: ./vega-web-master/server
      dockerfile: ./Dockerfile
    image: "venus/quantum"
    volumes:
      - ./vega-web-master/server:/app
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./vega-web-master
      dockerfile: ./Dockerfile
    image: "venus/theswitch"
    volumes:
      - ./vega-web-master:/app
    ports:
      - "3000:3000"
    links:
      - "backend-web:be"