# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr:
- develop

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a92a9da4-409c-454f-bcf4-1a3f6ba8acd0'
  imageRepository: 'vegaspringbackenddev'
  containerRegistry: 'seng426group10vega.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vega-spring-master/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: Test stage
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: JavaToolInstaller@0
      displayName: Install Java JDK 14
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: CmdLine@2
      displayName: Run mvnw test goal
      inputs:
        script: |
          chmod +x ./mvnw
          ./mvnw test
        workingDirectory: '$(Build.SourcesDirectory)/vega-spring-master'
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
