# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr:
- master
- develop

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '81ba4705-10e8-4ce2-b316-524a330882c4'
  imageRepository: 'vegawebfrontend'
  containerRegistry: 'seng426group10vega.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vega-web-master/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: Test stage
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      displayName: Install Node
      inputs:
        versionSpec: '16.7.0'
    - task: CmdLine@2
      displayName: Run unit tests
      inputs:
        script: npm install && npm test -- --watchAll=false
        workingDirectory: '$(Build.SourcesDirectory)/vega-web-master'
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
